# Generated by Django 5.2.4 on 2026-03-14 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_systemsetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmove',
            name='reference_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
